magazine_book/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('writers/', include('writers.urls')),

]

writers/urls.py
from django.urls import path

from . import views


app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:author_id>/books/', views.books, name='shell'),
]

writers/models.py
from django.db import models


class Author(models.Model):
    nickname = models.CharField(max_length=100)
    start_carrier = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nickname


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author,
                               on_delete=models.CASCADE,
                               related_name='books')
    length = models.IntegerField()
    published = models.DateField()

    def __str__(self):
        return self.title

writers/views.py
from django.shortcuts import render, get_object_or_404

from .models import Author


def index(request):
    authors = Author.objects.order_by('start_carrier')

    context = {
        'authors': authors
    }

    return render(request, 'index.html', context)


def books(request, author_id):
    query = {
        'id': author_id
    }

    author = get_object_or_404(Author, **query)

    context = {
        'author': author,
        'books': author.books.all()
    }

    return render(request, 'book-store.html', context)

writers/templates/book-store.html
{% load static %}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
<link rel="stylesheet" type="text/css" href="{% static 'writers/style_book-store.css' %}"/>
<title>Книги</title>
{#</head>#}
<body>
<h1> Книги: {{ author.nickname }}</h1>

<ol>

{% for book in books %}

    <h2>
        {{ book.title }}
    </h2>

    <p>Published - {{ book.published }}</p>

    <p>Length of pages {{ book.length }}</p>

{% endfor %}

</ol>
</body>
{#</html>#}

writers/templates/index.html
{% load static %}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
<title>Авторы</title>
<link rel="stylesheet" type="text/css" href="{% static 'writers/style.css' %}" />
{#</head>#}
{#<body>#}
<h1>Писатели</h1>

{% if authors %}

    <ol>
        {% for author in authors %}

            <h3>
                <li>
                    <a href="{% url 'books:shell' author.id %}"
                       title="started carrier at {{ author.start_carrier }}">

                        {{ author.nickname }}

                    </a>
                </li>
            </h3>


        {% endfor %}
    </ol>

{% else %}

    <p>No authors present.</p>

{% endif %}
{#</body>#}
{#</html>#}